apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-server-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::227769753445:role/mcp-server-secrets-irsa-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcp-server-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mcp-server-binding
subjects:
  - kind: ServiceAccount
    name: mcp-server-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: mcp-server-role
  apiGroup: rbac.authorization.k8s.io
