apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ema-backtester
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nagamsharathkumar9-spec/devops-project-1
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true